server:
  servlet:
    context-path: /configServer
  port: 9000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: aws
          uri: https://github.com/Naresh-doniparti/config-repo.git
          skip-ssl-validation: true
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: refresh